---
title: "ML Course Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

download the data

```{r}
train_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
test_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

train_filename <- "pml-training.csv"
test_filename <- "pml-testing.csv"

curl::curl_download(train_url, train_filename)
curl::curl_download(test_url, test_filename)
```


load training data

```{r}
library(tidyverse)
library(caret)
library(doParallel)

training <- read_csv(train_filename)

str(training) 

```
data cleaning / prep

```{r}
training_clean <- training %>%
        select(-c(1:7)) %>%
        mutate(classe = as_factor(classe)) %>%
        mutate_if(sapply(.,is.character), as.numeric)


# TODO 
# 1 deal with NAs

na_cols <-  training_clean %>%
        select(-classe) %>%
        pivot_longer(everything()) %>%
        group_by(name) %>%
        filter(value %>% is.na) %>%
        summarise(count = n()) %>%
        pivot_wider(names_from = name, values_from = count)
        

names(na_cols)

training_clean <- training_clean %>% select(-names(na_cols))

```

```{r}
#draw sample for quick fitting and testing preprocessing

sample <- sample_n(training_clean, 8000)

preProcSample = preProcess(sample, 
                           method = c("center", "scale"))

sample_trans <- predict(preProcSample, sample)


```


cross validation strategy

```{r}

trainControl <- trainControl(method = "repeatedcv",
                          number = 10,
                          repeats = 10,
                          allowParallel = TRUE)

```

random forest modelling

```{r}

no_cores = detectCores() -1
cl <- makePSOCKcluster(no_cores)
registerDoParallel(cl)


mod_tree <- train(
                  classe ~ ., 
                  method = "rf", 
                  data = sample_trans,
                  trControl = trainControl
                  )

stopCluster(cl)

saveRDS(mod_tree, file = "second_mod_tree")

mod_tree

```
Out of sample 



predict test set

```{r}
#read data
testing <- read_csv(test_filename)

#preProcess data
testing_clean <-  testing %>%
        select(-c(1:7)) %>%
        mutate_if(sapply(.,is.character), as.numeric)

#remove NA cols
testing_clean <- testing_clean %>% select(-names(na_cols))

testing_processed <- predict(preProcSample, testing_clean)

predict(mod_tree, testing_processed) %>%
        as_tibble() %>%
        mutate(row_num = row_number()) %>%
        select(row_num, value)


```


out of sample error

```{r}


```
































